[project]
name = "dbt-ihcrf"
version = "0.1.0"
description = "A dbt project for data transformations using uv package manager"
requires-python = ">=3.12"
dependencies = [
    "dbt-core==1.8.7",
    "dbt-postgres==1.8.2"
]
